#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#

# Attempt to set APP_HOME
PRG="\$0"
while [ -h "\$PRG" ]; do
    ls=\$(ls -ld "\$PRG")
    link=\$(expr "\$ls" : '.*-> \(.*\)$')
    if expr "\$link" : '/.*' > /dev/null; then
        PRG="\$link"
    else
        PRG=\$(dirname "\$PRG")"/\$link"
    fi
done
SAVED="\$(pwd)"
cd "\$(dirname "\$PRG\")/" >/dev/null
APP_HOME="\$(pwd -P)"
cd "\$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=\$(basename "\$0")

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

MAX_FD="maximum"

warn () {
    echo "\$*"
} >&2

die () {
    echo
    echo "\$*"
    echo
    exit 1
} >&2

OS_NAME=\$(uname -s)
case "\$OS_NAME" in
    Linux* )   OS_SPEC="linux";;
    Darwin* )  OS_SPEC="mac";;
    CYGWIN*|MINGW*|MSYS* ) OS_SPEC="windows";;
    *)         OS_SPEC="unknown";;
esac

CLASSPATH=\$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "\$CLASSPATH" ]; then
    echo "Downloading Gradle wrapper JAR..."
    GRADLE_WRAPPER_JAR_URL="https://raw.githubusercontent.com/gradle/gradle/v8.5.0/gradle/wrapper/gradle-wrapper.jar"
    if command -v curl > /dev/null 2>&1; then
        curl -s -L -o "\$CLASSPATH" "\$GRADLE_WRAPPER_JAR_URL"
    elif command -v wget > /dev/null 2>&1; then
        wget -q -O "\$CLASSPATH" "\$GRADLE_WRAPPER_JAR_URL"
    else
        die "ERROR: Neither curl nor wget found. Cannot download gradle-wrapper.jar"
    fi
    if [ ! -f "\$CLASSPATH" ]; then
        die "ERROR: Failed to download gradle-wrapper.jar"
    fi
fi

exec "\$JAVA_HOME/bin/java" \$DEFAULT_JVM_OPTS \$JAVA_OPTS \$GRADLE_OPTS \
    -classpath "\$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain "\$@"
